import { TeamMember } from "@/types";

export const TEAM_MEMBERS: Omit<
  TeamMember,
  "id" | "createdAt" | "updatedAt"
>[] = [
  {
    name: "Kishor Bhandari",
    role: "Full Stack Engineer",
    team: "Leadership",
    image: "/images/team/kishor-bhandari.JPEG",
    linkedin: "https://www.linkedin.com/in/kishor-bhandari",
    github: "https://github.com/kishorbhandari",
    skills: [
      "Leadership",
      "Strategy",
      "Full Stack Development",
      "Business Development",
    ],
    bio: "Visionary leader driving innovation and growth at Shrig Solutions. Expert in technology strategy and business development.",
  },
  {
    name: "Suman Dhakal",
    role: "AI Engineer",
    team: "Technology",
    image: "/images/team/suman-dhakal.svg",
    linkedin: "https://www.linkedin.com/in/suman-dhakal",
    github: "https://github.com/sumandhakal",
    skills: ["AI/ML", "Python", "TensorFlow", "System Architecture"],
    bio: "Technology leader specializing in AI/ML solutions and system architecture. Driving technical innovation across the organization.",
  },
  {
    name: "Ashlesh Pandey",
    role: "Lead Mobile Developer",
    team: "Mobile",
    image: "/images/team/ashlesh-pandey.svg",
    linkedin: "https://www.linkedin.com/in/ashlesh-pandey",
    github: "https://github.com/ashleshpandey",
    skills: ["React Native", "Flutter", "iOS", "Android"],
    bio: "Mobile development expert creating innovative cross-platform applications with focus on user experience and performance.",
  },
  {
    name: "Dipesh Thapa Magar",
    role: "Senior UI/UX Designer",
    team: "Design",
    image: "/images/team/dipesh-thapa-magar.svg",
    linkedin: "https://www.linkedin.com/in/dipesh-thapa-magar",
    github: "https://github.com/dipeshtmg",
    skills: ["UI/UX Design", "Figma", "Adobe Creative Suite", "WordPress"],
    bio: "Creative designer crafting beautiful and functional user experiences. Expert in modern design tools and WordPress development.",
  },
  {
    name: "Arjun Karki",
    role: "Senior Graphics Designer",
    team: "Design",
    image: "/images/team/arjun-karki.svg",
    linkedin: "https://www.linkedin.com/in/arjun-karki",
    github: "https://github.com/arjunkarki",
    skills: ["Branding", "Illustration", "Print Design", "Digital Art"],
    bio: "Visual design expert specializing in branding, illustration, and creative direction. Creating memorable brand experiences.",
  },
  {
    name: "Subba Saheb Chaudhary",
    role: "DevOps Engineer",
    team: "Infrastructure",
    image: "/images/team/subba-saheb-chaudhary.svg",
    linkedin: "https://www.linkedin.com/in/subba-saheb-chaudhary",
    github: "https://github.com/subbasaheb",
    skills: ["DevOps", "Docker", "Kubernetes", "AWS"],
    bio: "DevOps specialist ensuring smooth deployment and operations. Expert in cloud infrastructure and automation.",
  },
  {
    name: "Utsav Shrestha",
    role: "Mobile App Developer",
    team: "Mobile",
    image: "/images/team/utsav-shrestha.svg",
    linkedin: "https://www.linkedin.com/in/utsav-shrestha",
    github: "https://github.com/utsavshrestha",
    skills: ["React Native", "iOS", "Android", "Mobile UI"],
    bio: "Mobile app developer focused on creating intuitive and engaging user experiences across platforms.",
  },
  {
    name: "Suraj Paudel",
    role: "Flutter Developer",
    team: "Mobile",
    image: "/images/team/suraj-paudel.svg",
    linkedin: "https://www.linkedin.com/in/suraj-paudel",
    github: "https://github.com/surajpaudel",
    skills: ["Flutter", "Dart", "Firebase", "Mobile Development"],
    bio: "Flutter expert building beautiful and performant cross-platform mobile applications.",
  },
  {
    name: "Aman Rajbanshi",
    role: "QA Engineer",
    team: "Quality Assurance",
    image: "/images/team/aman-rajbanshi.svg",
    linkedin: "https://www.linkedin.com/in/aman-rajbanshi",
    github: "https://github.com/amanrajbanshi",
    skills: ["Testing", "Automation", "Selenium", "Quality Assurance"],
    bio: "Quality assurance specialist ensuring product excellence through comprehensive testing and automation.",
  },
  {
    name: "Raman Karki",
    role: "Full Stack Developer",
    team: "Web Development",
    image: "/images/team/raman-karki.svg",
    linkedin: "https://www.linkedin.com/in/raman-karki",
    github: "https://github.com/ramankarki",
    skills: ["Vue.js", "Laravel", "PHP", "Full Stack"],
    bio: "Full-stack developer with expertise in modern frameworks and backend technologies.",
  },
  {
    name: "Atisha Thapa",
    role: "Frontend Developer",
    team: "Web Development",
    image: "/images/team/atisha-thapa.svg",
    linkedin: "https://www.linkedin.com/in/atisha-thapa",
    github: "https://github.com/atishathapa",
    skills: ["React", "Vue.js", "CSS", "Frontend Development"],
    bio: "Frontend specialist creating engaging and responsive user interfaces with modern web technologies.",
  },
];
